CREATE TABLE IMAGE_DATA
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATA       BLOB
);

CREATE TABLE PRODUCT
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION   VARCHAR(255) NOT NULL,
    PRICE         BIGINT       NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IMAGE_DATA_ID BIGINT,
    FOREIGN KEY (IMAGE_DATA_ID) REFERENCES IMAGE_DATA (ID)
);